board: 6 Pack
name: MillingStation
meta: 2024-11-20

stepping:
  engine: I2S_STATIC
  idle_ms: 255
  pulse_us: 10
  dir_delay_us: 1
  disable_delay_us: 0

axes:
  shared_stepper_disable_pin: NO_PIN
  x:
    steps_per_mm: 80
    max_rate_mm_per_min: 3500.000
    acceleration_mm_per_sec2: 200.000
    max_travel_mm: 830.000
    soft_limits: false
    
    homing:
      cycle: 2
      positive_direction: false
      mpos_mm: 0
      feed_mm_per_min: 100.000
      seek_mm_per_min: 1800.000
      settle_ms: 300
      seek_scaler: 1.100
      feed_scaler: 1.100
    
    motor0:
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      limit_all_pin: gpio.32:low
      hard_limits: true
      pulloff_mm: 1.000
      tmc_5160:     
        cs_pin: gpio.16
        spi_index: 1   
        r_sense_ohms: 0.075
        run_amps: 2.0
        hold_amps: 1.8
        microsteps: 16
        stallguard: 0
        stallguard_debug: false
        toff_disable: 0
        toff_stealthchop: 5
        toff_coolstep: 3
        run_mode: StealthChop
        homing_mode: StealthChop
        use_enable: false
        step_pin: I2SO.9
        direction_pin: I2SO.10
        disable_pin: NO_PIN

  y:
    steps_per_mm: 79.85
    max_rate_mm_per_min: 3500.000
    acceleration_mm_per_sec2: 200.000
    max_travel_mm: 870.000
    soft_limits: false
    homing:
      cycle: 3
      positive_direction: false
      mpos_mm: 0
      feed_mm_per_min: 100.000
      seek_mm_per_min: 1800.000
      settle_ms: 300
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      limit_all_pin: gpio.33:low
      hard_limits: true
      pulloff_mm: 2.000
      tmc_5160:        
        spi_index: 2 
        r_sense_ohms: 0.075
        run_amps: 2.0
        hold_amps: 1.8
        microsteps: 16
        stallguard: 0
        stallguard_debug: false
        toff_disable: 0
        toff_stealthchop: 5
        toff_coolstep: 3
        run_mode: StealthChop
        homing_mode: StealthChop
        use_enable: false
        step_pin: I2SO.7
        direction_pin: I2SO.8:low
        disable_pin: NO_PIN
        
    motor1:
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 2.000
      tmc_5160:
        spi_index: 3         
        r_sense_ohms: 0.075
        run_amps: 2.0
        hold_amps: 1.8
        microsteps: 16
        stallguard: 0
        stallguard_debug: false
        toff_disable: 0
        toff_stealthchop: 5
        toff_coolstep: 3
        run_mode: StealthChop
        homing_mode: StealthChop
        use_enable: false
        step_pin: I2SO.4
        direction_pin: I2SO.5
        disable_pin: NO_PIN

  z:
    steps_per_mm: 1600
    max_rate_mm_per_min: 400.000
    acceleration_mm_per_sec2: 35.000
    max_travel_mm: 95.000
    soft_limits: false
    homing:
      cycle: 1
      positive_direction: true
      mpos_mm: 0.000
      feed_mm_per_min: 100.000
      seek_mm_per_min: 200.000
      settle_ms: 300
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      limit_all_pin: gpio.26:low
      hard_limits: true
      pulloff_mm: 2.000
      tmc_5160:  
        spi_index: 4       
        r_sense_ohms: 0.15
        run_amps: 1.2
        hold_amps: 1.2
        microsteps: 16
        stallguard: 0
        stallguard_debug: false
        toff_disable: 0
        toff_stealthchop: 5
        toff_coolstep: 3
        run_mode: StealthChop
        homing_mode: StealthChop
        use_enable: false
        step_pin: I2SO.1
        direction_pin: I2SO.2
        disable_pin: NO_PIN

i2so:
  bck_pin: gpio.22
  data_pin: gpio.21
  ws_pin: gpio.17

spi:
  miso_pin: gpio.19
  mosi_pin: gpio.23
  sck_pin: gpio.18

uart1:
  txd_pin: gpio.14
  rxd_pin: gpio.27
  rts_pin: NO_PIN
  baud: 9600
  mode: 8N1

uart_channel1:
  report_interval_ms: 75
  uart_num: 1

uart2:
 txd_pin: gpio.13
 rxd_pin: gpio.4
 baud: 9600
 mode: 8N1

ModbusVFD:
  model: DeltaMS300
  min_rpm: 6000
  max_rpm: 24000 
  uart_num: 2    
  modbus_id: 1    
  tool_num: 0
  off_on_alarm: false

sdcard:
  card_detect_pin: NO_PIN
  cs_pin: gpio.5
  frequency_hz: 8000000

control:
  safety_door_pin: gpio.36:low
  reset_pin: gpio.34:low
  feed_hold_pin: NO_PIN
  cycle_start_pin: gpio.39:low
  macro0_pin: gpio.25:low
  macro1_pin: NO_PIN
  macro2_pin: NO_PIN
  macro3_pin: NO_PIN

probe:
  pin: gpio.35:low
  check_mode_start: false

macros:
  startup_line0:
  startup_line1:
  macro0: $H
  macro1:
  macro2:
  macro3:

start:
  must_home: false
  deactivate_parking: false
  check_limits: false

parking:
  enable: true
  axis: Z
  pullout_distance_mm: 5.000
  pullout_rate_mm_per_min: 250.000
  target_mpos_mm: -5.000
  rate_mm_per_min: 800.000

i2c0:
  sda_pin: gpio.2
  scl_pin: gpio.15

oled:
  i2c_num: 0
  i2c_address: 60
  width: 128
  height: 64
  radio_delay_ms: 0
  flip: false
  mirror: false

status_outputs:
  report_interval_ms: 500
  idle_pin: I2SO.18
  run_pin: I2SO.19
  hold_pin: I2SO.20
  alarm_pin: I2SO.17
  door_pin: I2SO.21

#10V:
# forward_pin: NO_PIN
# reverse_pin: NO_PIN
# pwm_hz: 5000
# output_pin: gpio.12
# enable_pin: NO_PIN
# direction_pin: NO_PIN
# disable_with_s0: false
# s0_with_disable: true
# spinup_ms: 2000
# spindown_ms: 2000
# tool_num: 0
# speed_map: 0=0.000% 0=25% 6000=25% 12000=49.458% 23000=94.521% 24000=100.000%
# off_on_alarm: true

#relay:
#  direction_pin: NO_PIN
#  output_pin: NO_PIN
#  enable_pin: NO_PIN
#  disable_with_s0: false
#  s0_with_disable: true
#  spinup_ms: 0
#  spindown_ms: 0
#  tool_num: 0
#  speed_map: 0=0.000% 0=100.000% 1=100.000%
#  off_on_alarm: false

coolant:
  flood_pin: I2SO.15
  mist_pin: I2SO.6
  delay_ms: 0

#M62 P0 Activa el pin digital0. M63 P0 Desactiva pin digital0.
 # Salida digital 0: I2SO.23 (Autoapagado)
 # Salida digital 1: I2SO.14
 # Salida digital 2: I2SO.13
 # Salida digital 3: I2SO.12 
 # Salida digital 4: I2SO.11 
 # Salida digital 5: I2SO.16  

user_outputs:
  digital0_pin: I2SO.23   
  digital1_pin: I2SO.14 
  digital2_pin: I2SO.13
  digital3_pin: I2SO.12
  digital4_pin: I2SO.11
  digital5_pin: I2SO.16